CREATE DATABASE representante;
USE representante;

CREATE TABLE TB_Estados(
	SIGLA VARCHAR(2),
	NOME VARCHAR(100),
	RESPONSAVEL VARCHAR(60),

	PRIMARY KEY(SIGLA)
);

CREATE TABLE TB_Representantes(
	COD INT AUTO_INCREMENT,
	NOME VARCHAR(60),
	TELEFONE VARCHAR(20),
	EMAIL VARCHAR(50),
	ATUACAO VARCHAR(140),
	ESTADO VARCHAR(2),

	PRIMARY KEY(COD),
	FOREIGN KEY(ESTADO) REFERENCES TB_Estados(SIGLA)
);

CREATE TABLE TB_Users(
	LOGIN VARCHAR(30),
	NOME VARCHAR(60),
	SENHA VARCHAR(100),

	PRIMARY KEY(LOGIN)
);